### ISSUE TITLE
Update README for release

### ISSUE THREAD

**Issue by doneill** [Esri/maps-app-ios#48]
Some fixes required by the README before releasing publicly: 

**Getting Started**
- [x] Link to ArcGIS Runtime SDK should direct to [install guide](https://developers.arcgis.com/ios/latest/swift/guide/install.htm) as there is no direct reference. 

**Learn More**
- [x] Link to architecture returns 404. 

**Licensing**
- [x] Update the License.txt file to [LICENSE](https://github.com/Esri/mapbook-ios/blob/master/LICENSE) including the following `Copyright 2017 Esri`.

**3rd Party Component Licensing**
- [x] Link to SVProgressHUD license returns 404
- [x] Link to FlexiblePageControl license returns 404

**Comment by nixta** [comment]
Fixed with input from @doneill (thanks Dan!). See commit c235e6e19c098f13eedd21d7b0c977669e985e64
